import type { ScreeningConfig } from "@/types/screening";

export const PREVIEW_SCREENING_SLUG = "preview-screening";
export const PREVIEW_EVENT_SCREENING_SLUG = "preview-event";
export const PREVIEW_EXPIRED_EVENT_SCREENING_SLUG = "preview-expired-event";

export const previewScreeningConfig: ScreeningConfig = {
  slug: PREVIEW_SCREENING_SLUG,
  name: "Project RESET Preview Screening",
  institution: "The Virsa Foundation",
  eventDate: null,
  questionnaireKey: "reset-v1",
  questionnaireVersion: 1,
  policyVersion: "reset_data_use_v1_us",
  policyText:
    "I understand that my responses will be stored for Project RESET research and may contribute to anonymized or aggregated findings.",
  entryPathway: "non_event",
  rewardType: "trailer_access",
  eventWindowStatus: "non_event",
  checkInOpensAt: null,
  checkInClosesAt: null,
  accessEndsAt: null,
  questions: [
    {
      key: "burnout_signs",
      prompt: "How does burnout show up for you?",
      answerType: "multi_choice",
      position: 1,
      required: false,
      options: [
        "Exhausted",
        "Overwhelmed",
        "Anxious",
        "Numb",
        "Stuck",
        "Lonely",
        "Can't sleep",
        "Brain fog",
        "Emotional eating",
        "Never enough",
        "Reaching for junk food",
        "Skipping meals",
        "Living on takeout",
        "Chronic illness",
        "Gut problems",
        "Disconnected",
        "Cynical",
        "Constantly busy",
        "Compassion fatigue",
        "Climate anxiety",
        "Financial stress",
        "Other…",
      ].map((label, position) => ({
        key: label
          .toLowerCase()
          .replace(/[’']/g, "")
          .replace(/…/g, "")
          .replace(/[^a-z0-9]+/g, "_")
          .replace(/^_|_$/g, ""),
        label,
        position: position + 1,
      })),
    },
    {
      key: "burnout_note",
      prompt: "Tell us more",
      answerType: "text",
      position: 2,
      required: false,
      options: [],
    },
    {
      key: "reset_pathways",
      prompt: "What helps you reset?",
      answerType: "multi_choice",
      position: 3,
      required: false,
      options: [
        { key: "nourish", label: "Nourish", position: 1 },
        { key: "restore", label: "Restore", position: 2 },
        { key: "move", label: "Move", position: 3 },
        { key: "connect", label: "Connect", position: 4 },
        { key: "rebalance", label: "Rebalance", position: 5 },
      ],
    },
    {
      key: "reset_practices",
      prompt: "Which practices help?",
      answerType: "multi_choice",
      position: 4,
      required: false,
      options: [
        ["eating_more_plants", "Eating more plants", "nourish"],
        ["fruit_veg", "Fruit & veg", "nourish"],
        ["plant_protein", "Plant protein", "nourish"],
        ["cooking_at_home", "Cooking at home", "nourish"],
        ["less_ultra_processed", "Less ultra-processed", "nourish"],
        ["hydration", "Hydration", "nourish"],
        ["sleep", "Sleep", "restore"],
        ["breathwork", "Breathwork", "restore"],
        ["meditation", "Meditation", "restore"],
        ["reading", "Reading", "restore"],
        ["therapy", "Therapy", "restore"],
        ["walking", "Walking", "move"],
        ["strength", "Strength", "move"],
        ["yoga", "Yoga", "move"],
        ["dance", "Dance", "move"],
        ["sport", "Sport", "move"],
        ["friends", "Friends", "connect"],
        ["family", "Family", "connect"],
        ["animals", "Animals", "connect"],
        ["community", "Community", "connect"],
        ["volunteering", "Volunteering", "connect"],
        ["boundaries", "Boundaries", "rebalance"],
        ["journaling", "Journaling", "rebalance"],
        ["creative_work", "Creative work", "rebalance"],
        ["digital_detox", "Digital detox", "rebalance"],
        ["purpose", "Purpose", "rebalance"],
      ].map(([key, label, parentOptionKey], position) => ({
        key,
        label,
        parentOptionKey,
        position: position + 1,
      })),
    },
    {
      key: "reset_ritual",
      prompt: "Tell us about your RESET ritual",
      answerType: "text",
      position: 5,
      required: false,
      options: [],
    },
    {
      key: "burnout_custom_tags",
      prompt: "Participant-created burnout tags",
      answerType: "text",
      position: 6,
      required: false,
      options: [],
    },
    {
      key: "reset_custom_tags",
      prompt: "Participant-created RESET tags",
      answerType: "text",
      position: 7,
      required: false,
      options: [],
    },
  ],
};

export const previewEventScreeningConfig: ScreeningConfig = {
  ...previewScreeningConfig,
  slug: PREVIEW_EVENT_SCREENING_SLUG,
  name: "Project RESET Preview Event",
  entryPathway: "event",
  rewardType: "film_access",
  eventWindowStatus: "active_event",
  checkInOpensAt: "2026-08-01T00:00:00.000Z",
  checkInClosesAt: "2026-09-30T23:59:59.000Z",
  accessEndsAt: "2026-10-07T23:59:59.000Z",
};

export const previewExpiredEventScreeningConfig: ScreeningConfig = {
  ...previewScreeningConfig,
  slug: PREVIEW_EXPIRED_EVENT_SCREENING_SLUG,
  name: "Project RESET Expired Preview Event",
  eventWindowStatus: "event_expired",
  checkInOpensAt: "2026-08-01T00:00:00.000Z",
  checkInClosesAt: "2026-08-02T23:59:59.000Z",
};
